openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /staff:
    get:
      operationId: getStaff
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Staff'
    post:
      operationId: postStaff
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Staff'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
  /courses:
    get:
      operationId: getCourses
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseDetail'
    post:
      operationId: postCourses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseDetail'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseDetail'
components:
  schemas:
    Staff:
      required:
      - classes
      - office_id
      - staff_id
      - staff_name
      - title
      type: object
      properties:
        staff_id:
          type: integer
          format: int64
        office_id:
          type: integer
          format: int64
        staff_name:
          type: string
        title:
          type: string
        classes:
          type: array
          items:
            type: string
    CourseDetail:
      required:
      - code
      - course_id
      - credit
      - lecturers
      - name
      type: object
      properties:
        course_id:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
        credit:
          type: integer
          format: int64
        lecturers:
          type: array
          items:
            type: string
